### ISSUE TITLE
Change Mantis Version that is being installed

### ISSUE THREAD

**Issue by Hollow-Ego** [okainov/mantisbt-docker#11]
Hi there,
thank you for this amazing image. It worked the best out of all the images I tried.

I got a scenario where I need to specify the Mantis Version that is being installed, instead of using the newest version. Is there way to add it to the compose file as an optional parameter or something?

Thank you.

**Comment by okainov** [comment]
Hi!

You should be able to pull any of available old tags, I don't remove any of them https://hub.docker.com/r/okainov/mantisbt/tags

    docker pull okainov/mantisbt:2.24.1

Though if some version was missed (because I update directly to latest and it might happen that there will be a gap in between), of course, it won't be available

**Comment by Hollow-Ego** [comment]
Thanks for the quick reply.

That was the first thing I tried but the specific version I need is not available. The target version is 2.5.1, so quite old.

Do you have any clue or idea of what I could do then?

**Comment by okainov** [comment]
I can try to build it manually, but if it's really old, it might not work with current PHP versions and other things, in this case best recommendation would be to a) upgrade or b) try to build it yourself using Dockerfile from this repo.

**Comment by Hollow-Ego** [comment]
I see. Since I got no control over the Mantis installation I will see how I will go about this. 
Thank you for the feedback.
