### ISSUE TITLE
File Upload is 0

### ISSUE THREAD

**Issue by prelogic-greuter** [okainov/mantisbt-docker#5]
When using this Docker image, the File-Upload size is 0, thus mantis does not allow to upload a file.
I assume this is caused by PHP.ini, is there a way to set this value via configuration?

**Comment by okainov** [comment]
Thanks for the repot, I'll check it soon!

**Comment by GururajaUN** [comment]
@okainov , great effort in creating this dockerfile. This helps in many ways! Thank you for this repo..
Did you solve / have visibility on solving the attachment issue.

**Comment by okainov** [comment]
Sorry for taking so long. I've figured out what was the issue and will push a new version (with updated Mantis as well!) in a few mins!
